issuehunt: mgsisk
ko_fi: mgsisk
liberapay: mgsisk
open_collective: mgsisk
otechie: mgsisk
patreon: mgsisk
custom:
 - https://buymeacoff.ee/mgsisk
 - https://flattr.com/@mgsisk
 - https://paypal.me/mgsisk
