blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: /docs
    about: The docs should answer a lot of common questions
  - name: Discussions
    url: https://github.com/mgsisk/stencil/discussions
    about: Ask a question or start a discussion about this project
  - name: Contact
    url: https://otechie.com/mgsisk
    about: Contact the maintainer for direct assistance
